tamanho_antenas(A) :-
    pergunte(tamanho_antenas, 
    A,
    'Qual o tamanho das antenas em relação a cabeça do inseto?
Digite 1 para maiores e 2 para menores').

ocelos_presentes(A) :-
    pergunte(ocelos_presentes, 
    A,
    'Os ocelos estão presentes no inseto?
Digite 1 para sim e 2 não').

tarsos(A) :-
    pergunte(tarsos, 
    A,
    'Como são os tarsos anteriores?
Digite 1 para espatulados e 2 para não espatulados').

apice_abdominal(A) :-
    pergunte(apice_abdominal, 
    A,
    'Como é o ápice do abdomen?
Digite 1 para formando um tubo respiratório e 2 para sem sifão longo').

pernas_preensoras(A) :-
    pergunte(pernas_preensoras, 
    A,
    'As pernas do inseto são preensoras?
Digite 1 para sim e 2 para não, pernas posteriores longas').

membranas_hemielitro(A) :-
    pergunte(membranas_hemielitro, 
    A,
    'As membranas do hemiélitro possuem nervuras?
Digite 1 para sim e 2 para não').

coxas_medianas(A) :-
    pergunte(coxas_medianas, 
    A,
    'Como são as coxas medianas?
Digite 1 para mais próximas das posteriores do que das anteriores e 2 para eqüidistantes das anteriores e posteriores').

formato_corpo(A) :-
    pergunte(formato_corpo, 
    A,
    'Como é o formato de seu corpo?
Digite 1 para deprimido, alongado e 2 para não deprimido ou se deprimido apresenta-se ovalado').

hemielitro(A) :-
    pergunte(hemielitro, 
    A,
    'Os Hemiélitros são reticulados?
Digite 1 para sim, inteiramente e 2 para não').

escutelo(A) :-
    pergunte(escutelo, 
    A,
    'O escutelo estendende até ou além da metade do abdome?
Digite 1 para sim e 2 para não').

alcance_escutelo(A) :-
    pergunte(alcance_escutelo, 
    A,
    'Qual é o alcance do Escutelo?
Digite 1 para alcançando no máximo o ápice do clavo e 2 para escutelo cobrindo inteiramente ou quase o abdômen').

pernas_anteriores(A) :-
    pergunte(pernas_anteriores, 
    A,
    'Como são as pernas anteriores? 
Digite 1 para fossisiais e 2 para ambulatórias').

hemiélitro_cuneo(A) :-
    pergunte(hemiélitro_cuneo, 
    A,
    'Hemiélitros tem cúneo?
Digite 1 para sim e 2 para não').
 
### FALTANDO A QUESTAO 15
rostro(A) :-
    pergunte(rostro, 
    A,
    'Como é o rostro?
Digite 1 para Curto, grosso e 2 para longo').

antenomero_femur(A) :-
    pergunte(antenomero_femur, 
    A,
    'Como são o 4º antenômero e fêmur anterior?
Digite 1 para 4º antenômero clavado ou fusiforme; fêmur anterior muito dilatado e 2 para 4º antenômero não espessado; fêmures anteriores pouco dilatados').

corpo_pernas(A) :-
    pergunte(corpo_pernas, 
    A,
    ' Como é o corpo? E as pernas?
Digite 1 para Corpo muito fino, pernas medianas e posteriores muito alongadas e finas e 2 para corpo de forma diferente; pernas normais; hemiélitros divididos em cório e clavo').

nervuras_hemitelitro(A) :-
    pergunte(nervuras_hemitelitro, 
    A,
    'Quantas nervuras o membrana do hemiélitro tem?
Digite 1 para mais de 7 e 2 para menos de 7').

glandulas_odoriferas(A) :-
    pergunte(glandulas_odoriferas, 
    A,
    ' Glândulas odoríferas presentes?
Digite 1 para sim e 2 para não').

tamanho_cabeca(A) :-
    pergunte(tamanho_cabeca, 
    A,
    'Qual o tamanho da cabeça?
Digite 1 para mais estreita e mais curta que o pronoto e 2 para quase tão larga e tão longa quanto o pronoto').

caracteristicas(A) :-
    pergunte(caracteristicas, 
    A,
    'Corpo estreito; apêndices longos e finos; 1º antenômero e fêmures dilatados no ápice?
Digite 1 para sim e 2 para não').

ocelos_presentes(A) :-
    pergunte(tamanho_cabeca, 
    A,
    'Qual o tamanho da cabeça?
Digite 1 para mais estreita e mais curta que o pronoto e 2 para quase tão larga e tão longa quanto o pronoto').
